export const MenCollections = [
  {
    id: "m_sh_01",
    path: "collections/male/tshirts/1.jpg",
    type: "tops",
    category: "tshirt",
    displayName: "Men Blue Cotton T-Shirt",
    color: "blue",
    price: 649,
  },
  {
    id: "m_sh_02",
    path: "collections/male/tshirts/2.jpg",
    type: "tops",
    category: "tshirt",
    displayName: "Men Blue Cotton Crew-Neck T-Shirt",
    color: "blue",
    price: 699,
  },
  {
    id: "m_sh_03",
    path: "collections/male/tshirts/3.jpg",
    type: "tops",
    category: "tshirt",
    displayName: "Men Red Cotton V-Neck T-Shirt",
    color: "red",
    price: 599,
  },
  {
    id: "m_sh_04",
    path: "collections/male/tshirts/4.jpg",
    type: "tops",
    category: "tshirt",
    displayName: "Men Red Graphic Print Cotton T-Shirt",
    color: "red",
    price: 699,
  },
  {
    id: "m_sh_05",
    path: "collections/male/tshirts/5.jpg",
    type: "tops",
    category: "tshirt",
    displayName: "Men Navy-Blue Geek Graphic Cotton T-Shirt",
    color: "navy blue",
    price: 499,
  },
  {
    id: "m_sh_06",
    path: "collections/male/tshirts/6.jpg",
    type: "tops",
    category: "tshirt",
    displayName: "Men Black Graphic Cotton T-Shirt",
    color: "black",
    price: 649,
  },
  {
    id: "m_sh_07",
    path: "collections/male/tshirts/7.jpg",
    type: "tops",
    category: "tshirt",
    displayName: "Men Black Graphic Cotton T-Shirt",
    color: "black",
    price: 699,
  },
  {
    id: "m_sh_08",
    path: "collections/male/tshirts/8.jpeg",
    type: "tops",
    category: "tshirt",
    displayName: "Men Black Graphic Cotton T-Shirt",
    color: "black",
    price: 699,
  },
  {
    id: "m_sh_09",
    path: "collections/male/tshirts/9.jpeg",
    type: "tops",
    category: "tshirt",
    displayName: "Men Red World-Map Graphic Cotton T-Shirt",
    color: "red",
    price: 599,
  },
  {
    id: "m_sh_010",
    path: "collections/male/tshirts/10.jpg",
    type: "tops",
    category: "tshirt",
    displayName: "Men Grey Graphic Cotton T-Shirt",
    color: "grey",
    price: 399,
  },
  {
    id: "m_sh_011",
    path: "collections/male/tshirts/11.jpg",
    type: "tops",
    category: "tshirt",
    displayName: "Men Peach Graphic Cotton T-Shirt",
    color: "peach",
    price: 699,
  },
  {
    id: "m_sh_012",
    path: "collections/male/tshirts/12.jpg",
    type: "tops",
    category: "tshirt",
    displayName: "Men Green Graphic Cotton T-Shirt",
    color: "green",
    price: 499,
  },
  {
    id: "m_sh_013",
    path: "collections/male/tshirts/13.jpeg",
    type: "tops",
    category: "tshirt",
    displayName: "Men Brown Graphic Cotton T-Shirt",
    color: "brown",
    price: 3699,
  },
  {
    id: "m_sh_014",
    path: "collections/male/tshirts/14.jpg",
    type: "tops",
    category: "tshirt",
    displayName: "Men Blue Graphic Cotton T-Shirt",
    color: "blue",
    price: 699,
  },
  {
    id: "m_sh_015",
    path: "collections/male/tshirts/15.jpg",
    type: "tops",
    category: "tshirt",
    displayName: "Men Green Graphic Cotton T-Shirt",
    color: "green",
    price: 599,
  },
  {
    id: "m_sh_016",
    path: "collections/male/shorts/16.jpg",
    type: "bottoms",
    category: "shorts",
    displayName: "Men Blue Denim Shorts",
    color: "blue",
    price: 699,
  },
  {
    id: "m_sh_017",
    path: "collections/male/shorts/17.jpg",
    type: "bottoms",
    category: "shorts",
    displayName: "Men Blue Denim Shorts",
    color: "blue",
    price: 799,
  },
  {
    id: "m_sh_018",
    path: "collections/male/shorts/18.jpg",
    type: "bottoms",
    category: "shorts",
    displayName: "Men Black Casual Shorts",
    color: "black",
    price: 599,
  },
  {
    id: "m_sh_019",
    path: "collections/male/shorts/19.jpg",
    type: "bottoms",
    category: "shorts",
    displayName: "Men Green Casual Shorts",
    color: "green",
    price: 599,
  },
  {
    id: "m_sh_020",
    path: "collections/male/shorts/20.jpg",
    type: "bottoms",
    category: "shorts",
    displayName: "Men Brown Casual Shorts",
    color: "brown",
    price: 499,
  },
  {
    id: "m_sh_021",
    path: "collections/male/shorts/21.jpg",
    type: "bottoms",
    category: "shorts",
    displayName: "Men Black Casual Shorts",
    color: "black",
    price: 699,
  },
  {
    id: "m_sh_022",
    path: "collections/male/shorts/22.jpeg",
    type: "bottoms",
    category: "shorts",
    displayName: "Men Beige Casual Shorts",
    color: "beige",
    price: 699,
  },
  {
    id: "m_sh_023",
    path: "collections/male/shorts/23.jpeg",
    type: "bottoms",
    category: "shorts",
    displayName: "Men Grey Casual Shorts",
    color: "grey",
    price: 499,
  },
  {
    id: "m_sh_024",
    path: "collections/male/shirts/24.jpg",
    type: "tops",
    category: "shirts",
    displayName: "Men Purple Cotton Shirt",
    color: "purple",
    price: 799,
  },
  {
    id: "m_sh_025",
    path: "collections/male/shirts/25.jpg",
    type: "tops",
    category: "shirts",
    displayName: "Men Blue Cotton Shirt",
    color: "blue",
    price: 799,
  },
  {
    id: "m_sh_026",
    path: "collections/male/shirts/26.jpg",
    type: "tops",
    category: "shirts",
    displayName: "Men Blue Cotton Shirt",
    color: "blue",
    price: 699,
  },
  {
    id: "m_sh_027",
    path: "collections/male/shirts/27.jpg",
    type: "tops",
    category: "shirts",
    displayName: "Men Black Cotton Shirt",
    color: "black",
    price: 899,
  },
  {
    id: "m_sh_028",
    path: "collections/male/shirts/28.jpg",
    type: "tops",
    category: "shirts",
    displayName: "Men Purple Cotton Shirt",
    color: "purple",
    price: 599,
  },
  {
    id: "m_sh_029",
    path: "collections/male/shirts/29.jpg",
    type: "tops",
    category: "shirts",
    displayName: "Men Lavender Cotton Shirt",
    color: "purple",
    price: 699,
  },
  {
    id: "m_sh_030",
    path: "collections/male/shirts/30.jpg",
    type: "tops",
    category: "shirts",
    displayName: "Men Blue Cotton Shirt",
    color: "blue",
    price: 799,
  },
  {
    id: "m_sh_031",
    path: "collections/male/shirts/31.jpg",
    type: "tops",
    category: "shirts",
    displayName: "Men White Cotton Shirt",
    color: "white",
    price: 699,
  },
  {
    id: "m_sh_032",
    path: "collections/male/shirts/32.jpg",
    type: "tops",
    category: "shirts",
    displayName: "Men Blue Cotton Shirt",
    color: "blue",
    price: 699,
  },
  {
    id: "m_sh_033",
    path: "collections/male/shirts/33.jpg",
    type: "tops",
    category: "shirts",
    displayName: "Men Blue Cotton Shirt",
    color: "blue",
    price: 599,
  },
  {
    id: "m_sh_034",
    path: "collections/male/pyjamas/34.jpg",
    type: "bottoms",
    category: "pyjamas",
    displayName: "Men Blue Checkered Pyjamas",
    color: "blue",
    price: 599,
  },
  {
    id: "m_sh_035",
    path: "collections/male/pyjamas/35.jpg",
    type: "bottoms",
    category: "pyjamas",
    displayName: "Men Red Checkered Pyjamas",
    color: "red",
    price: 599,
  },
  {
    id: "m_sh_036",
    path: "collections/male/pyjamas/36.jpg",
    type: "bottoms",
    category: "pyjamas",
    displayName: "Men Green Checkered Pyjamas",
    color: "green",
    price: 699,
  },
  {
    id: "m_sh_037",
    path: "collections/male/pyjamas/37.jpg",
    type: "bottoms",
    category: "pyjamas",
    displayName: "Men Red Checkered Pyjamas",
    color: "red",
    price: 699,
  },
  {
    id: "m_sh_038",
    path: "collections/male/pyjamas/38.jpg",
    type: "bottoms",
    category: "pyjamas",
    displayName: "Men Yellow Checkered Pyjamas",
    color: "yellow",
    price: 599,
  },
  {
    id: "m_sh_039",
    path: "collections/male/pyjamas/39.jpg",
    type: "bottoms",
    category: "pyjamas",
    displayName: "Men Black Checkered Pyjamas",
    color: "black",
    price: 899,
  },
  {
    id: "m_sh_040",
    path: "collections/male/joggers/40.jpg",
    type: "bottoms",
    category: "joggers",
    displayName: "Men Beige Basic Joggers",
    color: "beige",
    price: 799,
  },
  {
    id: "m_sh_041",
    path: "collections/male/joggers/41.jpg",
    type: "bottoms",
    category: "joggers",
    displayName: "Men Black Basic Joggers",
    color: "black",
    price: 799,
  },
  {
    id: "m_sh_042",
    path: "collections/male/joggers/42.jpg",
    type: "bottoms",
    category: "joggers",
    displayName: "Men Peach Basic Joggers",
    color: "peach",
    price: 799,
  },
  {
    id: "m_sh_043",
    path: "collections/male/joggers/43.jpg",
    type: "bottoms",
    category: "joggers",
    displayName: "Men Black Basic Joggers",
    color: "black",
    price: 799,
  },
  {
    id: "m_sh_044",
    path: "collections/male/joggers/44.jpg",
    type: "bottoms",
    category: "joggers",
    displayName: "Men Beige Basic Joggers",
    color: "beige",
    price: 799,
  },
  {
    id: "m_sh_045",
    path: "collections/male/joggers/45.jpeg",
    type: "bottoms",
    category: "joggers",
    displayName: "Men Blue Basic Joggers",
    color: "blue",
    price: 799,
  },
  {
    id: "m_sh_046",
    path: "collections/male/joggers/46.jpeg",
    type: "bottoms",
    category: "joggers",
    displayName: "Men Brown Basic Joggers",
    color: "brown",
    price: 799,
  },
  {
    id: "m_sh_047",
    path: "collections/male/joggers/47.jpeg",
    type: "bottoms",
    category: "joggers",
    displayName: "Men Grey Basic Joggers",
    color: "grey",
    price: 799,
  },
  {
    id: "m_sh_048",
    path: "collections/male/jeans/48.jpg",
    type: "bottoms",
    category: "jeans",
    displayName: "Men Blue Denim Jeans",
    color: "blue",
    price: 999,
  },
  {
    id: "m_sh_049",
    path: "collections/male/jeans/49.jpg",
    type: "bottoms",
    category: "jeans",
    displayName: "Men Blue Denim Jeans",
    color: "blue",
    price: 999,
  },
  {
    id: "m_sh_050",
    path: "collections/male/jeans/50.jpg",
    type: "bottoms",
    category: "jeans",
    displayName: "Men Blue Denim Jeans",
    color: "blue",
    price: 999,
  },
  {
    id: "m_sh_051",
    path: "collections/male/jeans/51.webp",
    type: "bottoms",
    category: "jeans",
    displayName: "Men Black Denim Jeans",
    color: "black",
    price: 999,
  },
  {
    id: "m_sh_052",
    path: "collections/male/jeans/52.jpg",
    type: "bottoms",
    category: "jeans",
    displayName: "Men Blue Denim Jeans",
    color: "blue",
    price: 999,
  },
  {
    id: "m_sh_053",
    path: "collections/male/jeans/53.jpg",
    type: "bottoms",
    category: "jeans",
    displayName: "Men Grey Denim Jeans",
    color: "grey",
    price: 999,
  },
  {
    id: "m_sh_054",
    path: "collections/male/jeans/54.jpeg",
    type: "bottoms",
    category: "jeans",
    displayName: "Men Grey Denim Jeans",
    color: "grey",
    price: 999,
  },
  {
    id: "m_sh_055",
    path: "collections/male/jeans/55.jpeg",
    type: "bottoms",
    category: "jeans",
    displayName: "Men Black Denim Jeans",
    color: "black",
    price: 999,
  },
  {
    id: "m_sh_056",
    path: "collections/male/traditional/56.jpg",
    type: "one-pieces",
    category: "traditional",
    displayName: "Men Red Embroidered Cotton Short Kurta",
    color: "red",
    price: 1099,
  },
  {
    id: "m_sh_057",
    path: "collections/male/traditional/57.jpg",
    type: "one-pieces",
    category: "traditional",
    displayName: "Men Maroon Printed Cotton Kurta",
    color: "maroon",
    price: 1199,
  },
  {
    id: "m_sh_058",
    path: "collections/male/traditional/58.jpg",
    type: "one-pieces",
    category: "traditional",
    displayName: "Men Teal Sequin-Embroidered Kurta",
    color: "teal",
    price: 1299,
  },
  {
    id: "m_sh_059",
    path: "collections/male/traditional/59.jpg",
    type: "one-pieces",
    category: "traditional",
    displayName: "Men Teal-Black Brocade Kurta",
    color: "teal",
    price: 1399,
  },
];

export const WomenCollection = [
  {
    id: "f_sh_01",
    path: "collections/female/trousers/1.jpg",
    type: "bottoms",
    category: "trousers",
    displayName: "Women Beige High-Waisted Trousers",
    color: "beige",
    price: 899,
  },
  {
    id: "f_sh_02",
    path: "collections/female/trousers/2.jpeg",
    type: "bottoms",
    category: "trousers",
    displayName: "Women Brown High-Waisted Trousers",
    color: "brown",
    price: 899,
  },
  {
    id: "f_sh_03",
    path: "collections/female/trousers/3.jpeg",
    type: "bottoms",
    category: "trousers",
    displayName: "Women Black High-Waisted Trousers",
    color: "black",
    price: 899,
  },
  {
    id: "f_sh_04",
    path: "collections/female/trousers/4.jpeg",
    type: "bottoms",
    category: "trousers",
    displayName: "Women Black Slim-Fit Trousers",
    color: "black",
    price: 899,
  },
  {
    id: "f_sh_05",
    path: "collections/female/trousers/5.jpeg",
    type: "bottoms",
    category: "trousers",
    displayName: "Women Brown Slim-Fit Trousers",
    color: "brown",
    price: 899,
  },
  {
    id: "f_sh_06",
    path: "collections/female/trousers/6.jpeg",
    type: "bottoms",
    category: "trousers",
    displayName: "Women Beige Slim-Fit Trousers",
    color: "beige",
    price: 899,
  },
  {
    id: "f_sh_07",
    path: "collections/female/trousers/7.jpeg",
    type: "bottoms",
    category: "trousers",
    displayName: "Women Purple Slim-Fit Trousers",
    color: "purple",
    price: 899,
  },
  {
    id: "f_sh_08",
    path: "collections/female/trousers/8.jpeg",
    type: "bottoms",
    category: "trousers",
    displayName: "Women Peach Slim-Fit Trousers",
    color: "peach",
    price: 899,
  },
  {
    id: "f_sh_09",
    path: "collections/female/tops/9.jpg",
    type: "tops",
    category: "tops",
    displayName: "Women Maroon Off-Shoulder Top",
    color: "red",
    price: 599,
  },
  {
    id: "f_sh_010",
    path: "collections/female/tops/10.jpg",
    type: "tops",
    category: "tops",
    displayName: "Women Black Ribbed Knit Top",
    color: "black",
    price: 699,
  },
  {
    id: "f_sh_011",
    path: "collections/female/tops/11.jpg",
    type: "tops",
    category: "tops",
    displayName: "Women Peach Off-Shoulder Top",
    color: "peach",
    price: 599,
  },
  {
    id: "f_sh_012",
    path: "collections/female/tops/12.jpg",
    type: "tops",
    category: "tops",
    displayName: "Women Pink Floral Print Top",
    color: "pink",
    price: 499,
  },
  {
    id: "f_sh_013",
    path: "collections/female/tops/13.jpg",
    type: "tops",
    category: "tops",
    displayName: "Women Pink Sleeveless Top",
    color: "pink",
    price: 599,
  },
  {
    id: "f_sh_014",
    path: "collections/female/tops/14.jpg",
    type: "tops",
    category: "tops",
    displayName: "Women Pink Peplum Top",
    color: "pink",
    price: 599,
  },
  {
    id: "f_sh_015",
    path: "collections/female/tops/15.jpg",
    type: "tops",
    category: "tops",
    displayName: "Women Black Blouse Top",
    color: "black",
    price: 799,
  },
  {
    id: "f_sh_016",
    path: "collections/female/tops/16.jpg",
    type: "tops",
    category: "tops",
    displayName: "Women Yellow Lace-Detail Top",
    color: "yellow",
    price: 599,
  },
  {
    id: "f_sh_017",
    path: "collections/female/tops/17.jpg",
    type: "tops",
    category: "tops",
    displayName: "Women Brown Ribbed Tank Top",
    color: "brown",
    price: 499,
  },
  {
    id: "f_sh_018",
    path: "collections/female/tops/18.jpg",
    type: "tops",
    category: "tops",
    displayName: "Women Pink Ruffle-Sleeve Top",
    color: "pink",
    price: 399,
  },
  {
    id: "f_sh_019",
    path: "collections/female/tops/19.jpeg",
    type: "tops",
    category: "tops",
    displayName: "Women Brown Peplum Top",
    color: "brown",
    price: 699,
  },
  {
    id: "f_sh_020",
    path: "collections/female/shirts/20.jpeg",
    type: "tops",
    category: "shirts",
    displayName: "Women Brown Button-Down Shirt",
    color: "brown",
    price: 699,
  },
  {
    id: "f_sh_021",
    path: "collections/female/shirts/21.jpeg",
    type: "tops",
    category: "shirts",
    displayName: "Women Taupe Relaxed-Fit Shirt",
    color: "brown",
    price: 799,
  },
  {
    id: "f_sh_022",
    path: "collections/female/shirts/22.jpeg",
    type: "tops",
    category: "shirts",
    displayName: "Women Red Checkered Shirt",
    color: "red",
    price: 899,
  },
  {
    id: "f_sh_023",
    path: "collections/female/shirts/23.jpeg",
    type: "tops",
    category: "shirts",
    displayName: "Women Blue Classic Shirt",
    color: "blue",
    price: 399,
  },
  {
    id: "f_sh_024",
    path: "collections/female/shirts/24.jpeg",
    type: "tops",
    category: "shirts",
    displayName: "Women Red Checkered Shirt",
    color: "red",
    price: 699,
  },
  {
    id: "f_sh_025",
    path: "collections/female/shirts/25.jpg",
    type: "tops",
    category: "shirts",
    displayName: "Women Blue Classic Shirt",
    color: "blue",
    price: 899,
  },
  {
    id: "f_sh_026",
    path: "collections/female/shirts/26.jpg",
    type: "tops",
    category: "shirts",
    displayName: "Women Blue Classic Shirt",
    color: "blue",
    price: 799,
  },
  {
    id: "f_sh_027",
    path: "collections/female/jeans/27.jpg",
    type: "bottoms",
    category: "jeans",
    displayName: "Women Blue Slim-Fit Jeans",
    color: "blue",
    price: 999,
  },
  {
    id: "f_sh_028",
    path: "collections/female/jeans/28.jpg",
    type: "bottoms",
    category: "jeans",
    displayName: "Women Blue Slim-Fit Jeans",
    color: "blue",
    price: 999,
  },
  {
    id: "f_sh_029",
    path: "collections/female/jeans/29.jpg",
    type: "bottoms",
    category: "jeans",
    displayName: "Women Blue Slim-Fit Jeans",
    color: "blue",
    price: 999,
  },
  {
    id: "f_sh_030",
    path: "collections/female/jeans/30.jpg",
    type: "bottoms",
    category: "jeans",
    displayName: "Women Blue Slim-Fit Jeans",
    color: "blue",
    price: 999,
  },
  {
    id: "f_sh_031",
    path: "collections/female/jeans/31.jpg",
    type: "bottoms",
    category: "jeans",
    displayName: "Women Blue Slim-Fit Jeans",
    color: "blue",
    price: 999,
  },
  {
    id: "f_sh_032",
    path: "collections/female/dresses/32.jpg",
    type: "one-pieces",
    category: "dresses",
    displayName: "Women Green A-Line Dress",
    color: "green",
    price: 599,
  },
  {
    id: "f_sh_033",
    path: "collections/female/dresses/33.jpg",
    type: "one-pieces",
    category: "dresses",
    displayName: "Women Green A-Line Dress",
    color: "green",
    price: 599,
  },
  {
    id: "f_sh_034",
    path: "collections/female/dresses/34.jpg",
    type: "one-pieces",
    category: "dresses",
    displayName: "Women Pink Floral Print Dress",
    color: "pink",
    price: 699,
  },
  {
    id: "f_sh_035",
    path: "collections/female/dresses/35.jpeg",
    type: "one-pieces",
    category: "dresses",
    displayName: "Women Red Lace Midi Dress",
    color: "red",
    price: 799,
  },
  {
    id: "f_sh_036",
    path: "collections/female/dresses/36.jpg",
    type: "one-pieces",
    category: "dresses",
    displayName: "Women Peach Off-Shoulder Midi Dress",
    color: "peach",
    price: 699,
  },
  {
    id: "f_sh_037",
    path: "collections/female/dresses/37.jpg",
    type: "one-pieces",
    category: "dresses",
    displayName: "Women Green Pastel Fit-&-Flare Dress",
    color: "green",
    price: 599,
  },
  {
    id: "f_sh_038",
    path: "collections/female/dresses/38.jpg",
    type: "one-pieces",
    category: "dresses",
    displayName: "Women Black Bodycon Midi Dress",
    color: "black",
    price: 599,
  },
  {
    id: "f_sh_039",
    path: "collections/female/dresses/39.jpg",
    type: "one-pieces",
    category: "dresses",
    displayName: "Women Blue Wrap Midi Dress",
    color: "blue",
    price: 799,
  },
  {
    id: "f_sh_040",
    path: "collections/female/jeans/40.jpg",
    type: "one-pieces",
    category: "dresses",
    displayName: "Women Blue Floral Midi Dress",
    color: "blue",
    price: 899,
  },
  {
    id: "f_sh_041",
    path: "collections/female/kurta/41.jpg",
    type: "one-pieces",
    category: "kurta",
    displayName: "Women Yellow Floral Full-Sleeve Kurta",
    color: "yellow",
    price: 799,
  },
  {
    id: "f_sh_042",
    path: "collections/female/kurta/42.jpg",
    type: "one-pieces",
    category: "kurta",
    displayName: "Women Black Peacock-Print Full-Length Kurta",
    color: "black",
    price: 849,
  },
  {
    id: "f_sh_043",
    path: "collections/female/kurta/43.jpg",
    type: "one-pieces",
    category: "kurta",
    displayName: "Women Black Solid Kurta with Floral Embroidery",
    color: "black",
    price: 899,
  },
  {
    id: "f_sh_044",
    path: "collections/female/kurta/44.jpg",
    type: "one-pieces",
    category: "kurta",
    displayName: "Women Blue Sport-Tex Performance Kurta",
    color: "blue",
    price: 949,
  },
  {
    id: "f_sh_045",
    path: "collections/female/kurta/45.jpg",
    type: "one-pieces",
    category: "kurta",
    displayName: "Women Black Intricate Floral Kurta",
    color: "black",
    price: 999,
  },
];
    

export const man=["tshirt","joggers","pyjamas","jeans","shirts","shorts","traditional"]
export const woman = ["dresses", "jeans", "shirts", "tops", "trousers", "kurta"]

export const menCategories = [
  {
    name: "tshirt",
    path:"collections/categories/male/tshirt.jpg"
  },
  {
    name: "joggers",
    path:"collections/categories/male/joggers.png"
  },
  {
    name: "pyjamas",
    path:"collections/categories/male/pyjama.jpg"
  },
  {
    name: "jeans",
    path:"collections/categories/male/jeans.jpg"
  },
  {
    name: "shirts",
    path:"collections/categories/male/shirt.jpg"
  },
  {
    name: "shorts",
    path:"collections/categories/male/shorts.png"
  },
  {
    name: "traditional",
    path:"collections/categories/male/traditional.webp"
  }
]
export const womenCategories = [
  {
    name: "dresses",
    path:"collections/categories/female/dresses.png"
  },
  {
    name: "jeans",
    path:"collections/categories/female/jeans.jpg"
  },
  {
    name: "shirts",
    path:"collections/categories/female/shirt.jpg"
  },
  {
    name: "tops",
    path:"collections/categories/female/tops.jpg"
  },
  {
    name: "trousers",
    path:"collections/categories/female/trousers.jpg"
  },
  {
    name: "kurta",
    path:"collections/categories/female/kurta.jpg"
  },
]